import {
  Account,
  BASE_FEE,
  Contract,
  Keypair,
  TransactionBuilder,
  nativeToScVal,
  rpc,
  scValToNative,
} from '@stellar/stellar-sdk'

export type ChainVerdict = 'intact' | 'tampered' | 'unavailable' | 'not-anchored'

/**
 * Call `verify_latest(record_id, record_hash)` on the Record Registry contract
 * **directly** from the browser via Soroban RPC simulation.
 *
 * No EHR backend is involved. This is the trustless-verify path:
 * - The caller picks the RPC URL (it lives in the receipt itself).
 * - The read is a simulation; no signature, no fees, no network write.
 * - A compromised EHR backend cannot forge the result.
 */
export async function verifyLatestOnChain(args: {
  rpcUrl: string
  networkPassphrase: string
  contractId: string
  /** UUID hex with zero-padded tail — 64 hex chars = 32 bytes */
  recordIdHex32: string
  /** SHA-256 hex — 64 chars */
  recordHashHex: string
}): Promise<ChainVerdict> {
  const server = new rpc.Server(args.rpcUrl, { allowHttp: args.rpcUrl.startsWith('http://') })

  // Mock source: simulateTransaction doesn't require a funded account for a
  // read-only contract call. A random keypair gives us a valid pubkey shape.
  const kp = Keypair.random()
  const source = new Account(kp.publicKey(), '0')

  const contract = new Contract(args.contractId)

  const recordIdBytes = hexToBytes(args.recordIdHex32)
  const recordHashBytes = hexToBytes(args.recordHashHex)

  const tx = new TransactionBuilder(source, {
    fee: BASE_FEE,
    networkPassphrase: args.networkPassphrase,
  })
    .addOperation(
      contract.call(
        'verify_latest',
        nativeToScVal(recordIdBytes, { type: 'bytes' }),
        nativeToScVal(recordHashBytes, { type: 'bytes' }),
      ),
    )
    .setTimeout(30)
    .build()

  let sim: Awaited<ReturnType<typeof server.simulateTransaction>>
  try {
    sim = await server.simulateTransaction(tx)
  } catch (e) {
    console.error('[soroban] RPC unreachable:', e)
    return 'unavailable'
  }

  if (rpc.Api.isSimulationError(sim)) {
    console.error('[soroban] simulation error:', sim.error)
    // Could be a missing record_id key in contract storage — not tampering, not anchored.
    return 'unavailable'
  }

  // Extract the boolean return value from the simulation result.
  if (!rpc.Api.isSimulationSuccess(sim) || !sim.result) {
    return 'unavailable'
  }

  const raw = sim.result.retval
  const native = scValToNative(raw)

  if (native === true) return 'intact'
  if (native === false) {
    // The contract returned false. Two cases:
    // (a) record exists but hash differs → tampered
    // (b) record_id never anchored → not-anchored
    // verify_latest returns false in both cases. We can't distinguish without a
    // second call to get_latest_version; for now, return 'tampered' for the
    // noisier alert and let the UI optionally refine.
    return 'tampered'
  }
  console.error('[soroban] unexpected return value:', native)
  return 'unavailable'
}

/**
 * UUID → 32-byte hex with UUID in the first 16 bytes (mirror of backend
 * `uuid_to_bytes32_hex` so receipts generated by the backend verify cleanly).
 */
export function uuidToBytes32Hex(uuid: string): string {
  const hex = uuid.replace(/-/g, '').toLowerCase()
  if (hex.length !== 32 || !/^[0-9a-f]+$/.test(hex)) {
    return '00'.repeat(32)
  }
  return hex + '00'.repeat(16)
}

function hexToBytes(hex: string): Uint8Array {
  const clean = hex.startsWith('0x') ? hex.slice(2) : hex
  if (clean.length % 2 !== 0) throw new Error(`odd-length hex: ${clean.length}`)
  const out = new Uint8Array(clean.length / 2)
  for (let i = 0; i < out.length; i++) {
    out[i] = parseInt(clean.substr(i * 2, 2), 16)
  }
  return out
}
